openapi: 3.0.4
info:
  title: Go Svelte
  version: 0.1.0
paths:
  /ping:
    get:
      description: Check if backend is available
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"
  /entry:
    get:
      description: Get all entries
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntryList"
    post:
      description: Create new entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Entry"
      responses:
        "200":
          description: OK
          content:
            application/json: {}
        "400":
          description: Bad Request
components:
  schemas:
    Pong:
      type: object
      properties:
        result:
          type: string
          example: pong
      required:
        - result
    Entry:
      type: object
      properties:
        entry:
          type: string
          example: some entry
        id:
          type: integer
          example: 1
      required:
        - entry
        - id
    EntryList:
      type: array
      items:
        $ref: "#/components/schemas/Entry"
