// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

// Entry defines model for Entry.
type Entry struct {
	Entry string `json:"entry"`
	Id    int    `json:"id"`
}

// EntryList defines model for EntryList.
type EntryList = []Entry

// Pong defines model for Pong.
type Pong struct {
	Result string `json:"result"`
}

// PostEntryJSONRequestBody defines body for PostEntry for application/json ContentType.
type PostEntryJSONRequestBody = Entry
